---
- hosts: localhost
  remote_user: root
  roles:
    - ./vault-ssh-signer-role

- hosts: AddedNode
  remote_user: root
  vars:
    ansible_ssh_private_key_file: "{{ r_tempfile.path }}/id_rsa"
    ansible_ssh_extra_args: "{{ r_tempfile.path }}/signed"
  roles:
    - ./get-node-stat
