---
- hosts: localhost
  remote_user: root
  roles:
    - ./vault-ssh-signer-role

- hosts: AddedNode
  remote_user: root
  vars:
    ansible_ssh_private_key_file: "{{ hostvars['localhost']['r_tempfile']['path'] }}/id_rsa"
    ansible_ssh_extra_args: "-i {{ hostvars['localhost']['r_tempfile']['path'] }}/signed"
  roles:
    - ./get-node-stat
